services:
  catalog-app:
    image: catalog-app/catalog-app:latest
    container_name: catalog-app
    restart: always
    env_file:
      - .env.production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - catalog-app:/app
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}']
      interval: 5s
      retries: 5
    networks:
      - app-network

volumes:
  catalog-app:
  postgres_data:

networks:
  app-network:
    driver: bridge
